# Docker Compose Configuration for Redis Master-Slave Setup
version: "3.3"
services:
  # Redis Master Service
  redis-master:
    image: redis:6.0.7  
    container_name: redis-master  
    restart: always
    volumes:
      - redis_master:/data  
    ports:
      - 6379:6379 
    networks:
      - redis-net  

  # Redis Slave 1 Service
  redis-organization:
    image: redis:6.0.7  
    container_name: redis-organization 
    restart: always 
    volumes:
      - redis_organization:/data 
    ports:
      - 6479:6379
    command: redis-server --slaveof redis-master 6379
    networks:
      - redis-net 

  # Redis Slave 2 Service
  redis-passwords:
    image: redis:6.0.7 
    container_name: redis-passwords
    restart: always  
    volumes:
      - redis_passwords:/data  
    ports:
      - 6579:6379  
    command: redis-server --slaveof redis-master 6379 
    networks:
      - redis-net

  # Redis Slave 3 Service
  redis-products:
    image: redis:6.0.7  
    container_name: redis-products  
    restart: always
    volumes:
      - redis_products:/data 
    ports:
      - 6679:6379 
    command: redis-server --slaveof redis-master 6379  
    networks:
      - redis-net  

# Docker Volumes
volumes:
  redis_master:  
  redis_organization:   
  redis_passwords:  
  redis_products: 

# Docker Network Configuration
networks:
  redis-net:
    driver: bridge 
